apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
type: Opaque
data:
  connStrings.db: {{ .Values.secrets.connStrings.db | b64enc | quote}}
  connStrings.redis: {{ .Values.secrets.connStrings.redis | b64enc | quote}}
  connStrings.amqp: {{ .Values.secrets.connStrings.amqp | b64enc | quote}}
  jwtConfig.privateKey: {{ .Values.secrets.jwtConfig.privateKey | b64enc | quote}}
  jwtConfig.publicKey: {{ .Values.secrets.jwtConfig.publicKey | b64enc | quote}}
  jwtConfig.refreshTokenSecret: {{ .Values.secrets.jwtConfig.refreshTokenSecret | b64enc | quote}}
  smtpConfig.password: {{ .Values.secrets.smtpConfig.password | b64enc | quote}}
  smtpConfig.username: {{ .Values.secrets.smtpConfig.username | b64enc | quote}}
  smtpConfig.host: {{ .Values.secrets.smtpConfig.host | b64enc | quote}}
  smtpConfig.port: {{ .Values.secrets.smtpConfig.port | b64enc | quote}}
  smtpConfig.useSsl: {{ .Values.secrets.smtpConfig.useSsl | b64enc | quote}}
  smtpConfig.defaultCredentials: {{ .Values.secrets.smtpConfig.defaultCredentials | b64enc | quote}}

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
