app = "auth-service-floral-smoke-8144"
primary_region = "gru"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 1
processes = [ "app" ]

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"

[[vm]]
size = "shared-cpu-2x"
