name: Trigger auto deployment for auth-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/auth-service-AutoDeployTrigger-884c9176-33c2-4200-bbe3-4c09d4e73ffa.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AUTHSERVICE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: myappsrepolg.azurecr.io
          registryUsername: ${{ secrets.AUTHSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AUTHSERVICE_REGISTRY_PASSWORD }}
          containerAppName: auth-service
          resourceGroup: my-apps-group
          imageToBuild: myappsrepolg.azurecr.io/auth-service:${{ github.sha }}
          dockerfilePath: Dockerfile

     

